# Generated by Django 4.0.1 on 2022-12-21 15:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.BigIntegerField(verbose_name='Telegram chat_id')),
                ('tg_user_id', models.BigIntegerField(unique=True, verbose_name='Telegram user_id')),
                ('tg_username', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Пользователь Telegram')),
                ('verification_code', models.CharField(max_length=15, unique=True, verbose_name='Код верификации')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
        ),
    ]
