# Generated by Django 4.0.1 on 2022-12-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_tguser_options_alter_tguser_tg_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Telegram_username'),
        ),
    ]
