# Generated by Django 4.0.1 on 2022-12-21 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_tguser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_chat_id',
            field=models.BigIntegerField(verbose_name='tg_chat_id'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_user_id',
            field=models.BigIntegerField(unique=True, verbose_name='tg_user_id'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_username',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='tg_username'),
        ),
    ]
